---
git:
  depth: 10
sudo: false
language: node_js
cache: yarn

node_js:
- '7'
- '6'
- '4'

script:
- 'if [ -n "${LINT-}" ]; then yarn run lint ; fi'
- yarn run test-ci

matrix:
  fast_finish: true
  include:
    - node_js: "node"
      env: LINT=true

after_success: yarn run coverage-ci
