---
git:
  depth: 10
sudo: false
language: node_js
cache: yarn

node_js:
- '8'
- '6'
- '4'

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.2
- export PATH=$HOME/.yarn/bin:$PATH

before_script:
- yarn run bootstrap && yarn run build

script:
- if [ -n "${LINT-}" ]; then yarn run lint ; fi
- if [ -z "${SKIPTESTS-}" ]; then yarn run coverage; fi

matrix:
  include:
    - node_js: "node"
      env: LINT=true SKIPTESTS=true

after_success: yarn run coverage-ci
