---
git:
  depth: 10
sudo: false
language: node_js
cache: yarn

node_js:
- '8'
- '6'
- '4'

before_script:
- yarn run bootstrap && yarn run build && yarn run build-standalone

script:
- if [ -n "${LINT-}" ]; then yarn run lint ; fi
- if [ -z "${SKIPTESTS-}" ]; then yarn run coverage; fi

matrix:
  include:
    - node_js: "node"
      env: LINT=true SKIPTESTS=true

after_success: yarn run coverage-ci
