init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: '9'
    - nodejs_version: '8'
    - nodejs_version: '6'
    - nodejs_version: '4'

cache:
 - "%LOCALAPPDATA%\\Yarn"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install -g yarn@1.3.2
  - set PATH=%APPDATA%\npm;%PATH%
  - yarn

matrix:
  fast_finish: true

build: 'off'

shallow_clone: true

before_test:
  - cmd: yarn build

test_script:
  - node --version
  - yarn --version
  - yarn test
