version: 2.1

aliases:
  - &restore-node-modules-cache
    keys:
      - v1-yarn-deps-{{ checksum "yarn.lock" }}
      - v1-yarn-deps-

  - &restore-yarn-cache
    keys:
      - v1-1-yarn-cache-{{ checksum "yarn.lock" }}
      - v1-1-yarn-cache-

  - &save-node-modules-cache
    paths:
      - node_modules
    key: v1-yarn-deps-{{ checksum "yarn.lock" }}

  - &save-yarn-cache
    paths:
      - ~/.cache/yarn
    key: v1-1-yarn-cache-{{ checksum "yarn.lock" }}

executors:
  node-executor:
    docker:
      - image: circleci/node:latest
    working_directory: ~/babel/minify

jobs:
  build:
    executor: node-executor
    parallelism: 4
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - restore_cache: *restore-yarn-cache
      - restore_cache: *restore-node-modules-cache
      - run: yarn
      - run: yarn build
      # Save dependency cache
      - save_cache: *save-node-modules-cache
      - save_cache: *save-yarn-cache
      # Test
      - run: ./smoke/circleci.sh
      # Save test results
      - store_test_results:
          path: /tmp/circleci-test-results
      # Save artifacts
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results
